language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: QniEFp26dKuk6U3zGjMChWS2nQeKTnD7Jx9OLV4sTNQLQlVMwwi2yhuPJIt4iSali8oJ0V70lcnRd6cXyTPjy65z1eX5bgXde8Y10+Dsd3W1+K2vthJ4Vz5Y15wh2eepixRdRY4rUPhj06nE2u8U1Y92SAyNhT+sq2lXwqfsieyKusNhxVVcchfgYZqmCvk60O0PrQfjSEmgdIOEvik+/QkSbzS4IbkQZEYzppR6cWnQ1elxJG6MrsY4KNY01WShgRDgxGif2robE0SZtkvXWlCTOPR1y0NqTTHvI6UEk4ERbpqC4QimUFs9fEm6q2tNGJ6z0XvpEI2gp4355hmuzPydiSZcKlxaBK2qXDtbrAZYStgCwTpe5PLJ03/OJahAYdJRouSktnKswMT22p8z+7xcUp6UryGzdCQpxoP63AXklstzosXcWDM3XIXOD06aM/E7lBH2QmXb99ZcYf4Pl8zX7GOhk6ugBHeFFES8d2C+J5m2gQSHNmWr5GHWnezAzASwIDrsuhF/ZGsBIpgogFWkcVeuUv5A5OelK1yT1jvejZwLX6MLb/MHK1HgRLhmwNzzK2ZPAv0jxDbTMv9REmW1HpQBBUeIrQz54JWXhT/tpZJQwbka9AVyP/HWOYGXlveEGoxpd1vNOwOjBL9dPYgkIvrK6FbTMCj8XDc+eA4=
  app: diego-task-manager
  on:
    repo: diegomichell/Task-Manager
